# MUIC_UNIVERSAL
obj-$(CONFIG_MUIC_UNIVERSAL)		+= muic_task.o
obj-$(CONFIG_MUIC_UNIVERSAL)		+= muic_state.o
obj-$(CONFIG_MUIC_UNIVERSAL)		+= muic_apis.o
obj-$(CONFIG_MUIC_UNIVERSAL)		+= muic_sysfs.o
obj-$(CONFIG_MUIC_UNIVERSAL)		+= muic_debug.o
obj-$(CONFIG_MUIC_UNIVERSAL)		+= muic_dt.o
obj-$(CONFIG_MUIC_UNIVERSAL)		+= muic_i2c.o
obj-$(CONFIG_MUIC_UNIVERSAL)		+= muic_regmap.o
obj-$(CONFIG_MUIC_UNIVERSAL)		+= muic_vps.o
obj-$(CONFIG_MUIC_UNIVERSAL_SM5703)	+= muic_regmap_sm5703.o
